### ISSUE TITLE
Implement SecureRandom

### ISSUE THREAD

**Issue by aslesarenko** [anon-br/sigmajs-crypto-facade#1]
Currently Sigma.js uses scala.util.Random for generation of random bytes.
This is not a proper secure source of randomness. 
This issue is to implement SecureRandom class

**Comment by arobsn** [comment]
* Added `CryptoFacade.getRandomBytes()` using `crypto.getRandomValues` which defers to the OS. ([#d417056](https://github.com/arobsn/sigmajs-crypto-facade/commit/d417056593d6ca409630e4079f9a8c7808233128))
* Released as `sigmajs-crypto-facade@0.0.7`
